---
title: ""
output:
  html_document:
    css: "syllabus.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h2 style="text-align: center;" class="info-general">
  PSY 384 Q : Advanced Applied Statistics I
</h2>

<p class="info-general">
  **Class Location:** SEA 3.250
</p>
  
<p class="info-general">
  **Class Time:** Mondays and Wednesdays 10:00 am - 11:30 am
</p>

<p class="info-general">
  **Instructor:** Manuel Villarreal
</p>

<p class="info-general">
  **Contact:** <br>
  <ul>
    <li>
      Office: SEA 5.230
    </li>
    <li>
      email: jesusmvu@utexas.edu
    </li>
</ul>
</p>

<h4>
  Course Purpose:
</h4>
<p class="description-section">
  The purpose of this course is to introduce students to the application of some
  advanced statistical techniques, such as robust linear models, generalized
  linear models, and maximum likelihood estimation. This course is mainly 
  applied, which means that the focus will be in how to use these techniques 
  with "real" data. However, in order to use them properly  we will of course 
  have to learn some theory. Computations and data visualizations will be 
  handled using the R/RStudio computing environment.
</p>

<h4>
  Instructional Methods:
</h4>
<p class="description-section">
  Substantive materials will be delivered in the form of lectures and class activities. 
  These activities will be in the form of case studies were we will apply the methods we 
  have learned to real data during class.
</p>

<h4>
  Office Hours:
</h4>
<p class="description-section">
  Tuesdays 3:00 pm - 4:00 pm in SEA 5.230. You can also email me to schedule an
  appointment. 
</p>

<h4>
  Materials:
</h4>
<p class="description-section">
  In addition to whatever you use to take notes, you will need to bring a laptop
  with R/Rstudio installed to complete and submit in-class activities.
</p>

<h4>
Textbook:
</h4>
<p class="description-section">
  There is no required textbook for this class. We will primarily be using
  lectures and and RMarkdown files for in class case studies and homework
  problems, all of which will be provided via Canvas. Some supplementary
  resources are:
  <ul>
    <li>
      Alan Agresti (2012). Categorical Data Analysis. *Third edition*.
    </li>
  </ul>
<p>

<h4>
  Assignments:
</h4>
<p class="description-section">
  There are two type of assignments for this class, take home case studies, 
  and a final project. Take home case studies will be in the form of an 
  RMarkdown file that describes a scientific problem. Your task will be 
  to find a way to answer the posed research question using the methods 
  learned in class, and write the results in a format that resembles the
  "Results" section of a paper. The final project will be a research report
  no more than 5 pages long. This research report can be based on data that 
  you have collected before or simmulated data, however, it should have the
  structure of a research paper (with a small introduction, methods, results, 
  etc.)
</p>

<h4>
  Grades:
</h4>
<p class="description-section">
  Grades will be based on three components: in class participation (completion 
  of in-class case studies), homeworks (no more than 6), and final project, 
  with a weight of 20, 45, and 35% respectively. For the determination of letter 
  grades at the end of the class, I will use my predecessor’s graduate class 
  grading scale: A=80+, B=60-79.99, C=59.99-and-below. The graduate school 
  now uses +/- designations in addition to simple letter grades:
  <ul>
    <li>
      a "+" is earned for a final grade in the upper third of the interval.
    </li>
    <li>
      the letter only for a final grade in the middle third.
    </li>
    <li>
      a "-" for a final grade in the lower third of the interval.
    </li>
  </ul>
  **Note:** the graduate school does not allow an A+ designation.
</p>

<h4>
  A University-wide note:
</h4>
<p class="description-section">
  The University of Texas at Austin provides upon request appropriate academic
  accommodations for qualified students with disabilities. For more information
  visit: https://diversity.utexas.edu/disability/
</p>

<h4 style="margin-bottom: 0.5cm;">
  Class topics (subject to change):
</h4>
<p>
  Linear models (Review):
  <ol type="i">
    <li>
      Simple linear regression
    </li>
    <li>
      Multivariate linear regression
    </li>
    <li>
      General linear model (change of basis functions)
    </li>
  </ol>
  Robust Regression Models
  <ol type="i">
    <li>
      Robust variance estimation
    </li>
    <li>
      Quantile regression (loss functions)
    </li>
    <li>
      Introduction to splines
    </li>
  </ol>
  Generalized Linear Models
  <ol type="i">
    <li>
      Introduction to GLM with count data
    </li>
    <li>
      Iteratively Re-weighted Least Squares estimation
    </li>
    <li>
      The Poisson model
    </li>
    <li>
      The Binomial model
    </li>
    <li>
      Link functions
    </li>
  </ol>
  Maximum Likelihood Estimation (custom models)
  <ol>
    <li>
      Introduction to MLE's (the normal model)
    </li>
    <li>
      The binomial model (example with exponential decay)
    </li>
    <li>
      Inference with MLE's and parameter transformations
    </li>
    <li>
      Custom likelihood functions in R/Rstudio
    </li>
  </ol>
</p>
